version: '3.8'

services:
  streamlit-dashboard:
    build: .
    container_name: nifty_dashboard
    ports:
      - "8501:8501"
    restart: unless-stopped
    command: ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]

  fastapi-backend:
    build: .
    container_name: nifty_api
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: ["python3", "-m", "uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000"]
